listener 1883
allow_anonymous false
password_file /mosquitto/config/passwords
acl_file /mosquitto/config/acl
persistence true
persistence_location /mosquitto/data/
message_size_limit 4096
max_queued_messages 256
log_dest stdout
