const {chromium}=require('playwright');
const fs=require('fs');const http=require('http');const path=require('path');
(async()=>{
const root=path.resolve(__dirname,'../app/web');
const server=http.createServer((req,res)=>{let file=req.url==='/'?'index.html':req.url.replace('/assets/','');if(!['index.html','style.css','app.js','desktop.js'].includes(file)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(path.join(root,file)));});
await new Promise(r=>server.listen(8766,'127.0.0.1',r));
const browser=await chromium.launch({headless:true,channel:'chrome'});const page=await browser.newPage({viewport:{width:1600,height:1080}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{
  window.__spoken=[];
  window.SpeechSynthesisUtterance=class {constructor(text){this.text=text;}};
  Object.defineProperty(window,'speechSynthesis',{value:{getVoices:()=>[],cancel:()=>{},speak:utterance=>{window.__spoken.push(utterance.text);utterance.onstart?.();}}});
});
await page.route('**/session/login',route=>route.fulfill({json:{access_token:'test-browser-session'}}));
await page.route('**/session/refresh',route=>route.fulfill({status:401,json:{detail:'Login required'}}));
await page.route('**/knowledge',route=>route.fulfill({json:route.request().method()==='GET'?[]:{id:'saved'}}));
await page.route('**/vision',route=>route.fulfill({json:{text:'Causa provável: variável não definida. Defina a variável antes do uso.'}}));
await page.route('**/desktop/propose',route=>route.fulfill({json:{token:'desktop_testtoken01234567890',description:'git add: app.py',detail:'app.py | 1 +'}}));
await page.route('**/desktop/confirm',route=>route.fulfill({json:{message:'Operação concluída.'}}));
await page.route('**/system/status',route=>route.fulfill({json:{model:'qwen3:8b',provider:'ollama',memory_enabled:true,timezone:'America/Sao_Paulo',max_input_chars:4000,home_actions:[],status:'missing_model',message:'Modelo não instalado neste Ollama. Execute ollama pull qwen3:8b.'}}));
await page.route('**/history',route=>route.fulfill({json:[{session:'saved',title:'Conversa salva'}]}));
await page.route('**/history/saved',route=>route.fulfill({json:[{human:'Mensagem anterior',answer:'Resposta anterior'}]}));
let sentModel=null;
await page.route('**/chat/stream',route=>{sentModel=route.request().postDataJSON().model;return route.fulfill({contentType:'application/x-ndjson',body:[{type:'reset'},{type:'token',text:'Parcial'},{type:'answer',text:'<img src=x onerror=alert(1)> Resposta de teste.'},{type:'done',text:'<img src=x onerror=alert(1)> Resposta de teste.',pending_actions:[],warnings:[]}].map(x=>JSON.stringify(x)).join('\n')+'\n'});});
await page.goto('http://127.0.0.1:8766');await page.fill('#token','test-token-01234567890123456789012345');await page.locator('#auth button').first().click();await page.waitForFunction(()=>document.querySelector('#core-state').textContent==='MODELO AUSENTE');
await page.screenshot({path:'jarvis-dashboard-desktop.png',fullPage:true});
await page.check('#speak');await page.fill('#prompt','Olá');await page.click('#send');await page.waitForSelector('.bubble.assistant');if(await page.locator('#messages img').count())throw Error('Unsafe model HTML');
await page.waitForFunction(()=>document.querySelector('#send').disabled===false);
if(await page.locator('#presence').getAttribute('data-state')!=='speaking')throw Error('Avatar must follow speech start');
if(await page.evaluate(()=>window.__spoken.length)!==1)throw Error('Answer spoken more than once');
await page.click('#avatar-stop');
if(await page.locator('#presence').getAttribute('data-state')!=='idle')throw Error('Avatar must stop with speech');
if(!await page.locator('#response-time').textContent().then(t=>t.includes('Primeiro texto em')))throw Error('First text timing absent');
await page.uncheck('#speak');
await page.unroute('**/system/status');
await page.route('**/system/status',route=>route.fulfill({json:{model:'combo-casa',provider:'omniroute',memory_enabled:true,timezone:'America/Sao_Paulo',max_input_chars:4000,home_actions:[],status:'available',models:['provider/model-a','provider/model-b'],message:'Catálogo disponível.'}}));
await page.click('#refresh');await page.waitForFunction(()=>document.querySelector('#core-state').textContent==='GATEWAY ACESSÍVEL');
await page.fill('#model-filter','model-b');if(await page.locator('#catalog code').count()!==1)throw Error('Catalog filter failed');
await page.selectOption('#model-select','provider/model-b');
await page.fill('#prompt','Use o modelo selecionado');await page.click('#send');await page.waitForFunction(()=>document.querySelector('#send').disabled===false);
if(sentModel!=='provider/model-b')throw Error('Selected model was not sent');
await page.locator('#history-list button').first().click();await page.waitForFunction(()=>document.querySelector('#messages').textContent.includes('Mensagem anterior'));
await page.click('#focus');if(!await page.locator('body').evaluate(e=>e.classList.contains('focus-mode')))throw Error('Focus mode');await page.click('#focus');
await page.fill('#debug-text','NameError: name example is not defined');await page.check('#debug-screen');await page.click('#analyze-screen');await page.waitForFunction(()=>document.querySelector('#vision-result').textContent.includes('Causa provável'));
await page.click('#save-debug');if(await page.inputValue('#knowledge-category')!=='resolved_error')throw Error('Debugger memory category');
await page.selectOption('#desktop-action','git_add');await page.fill('#desktop-alias','jarvis');await page.fill('#git-paths','app.py');await page.click('#desktop-review');await page.waitForSelector('#desktop-plan button');await page.locator('#desktop-plan button').click();await page.waitForFunction(()=>document.querySelector('#notice').textContent==='Operação concluída.');
if(await page.locator('#gateway a').getAttribute('target')!=='_self')throw Error('Gateway must stay in same tab');
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'jarvis-dashboard-mobile.png',fullPage:true});
if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile overflow: '+await page.evaluate(()=>Array.from(document.querySelectorAll('body *')).filter(e=>e.getBoundingClientRect().right>innerWidth).map(e=>e.tagName+'.'+e.className).join(', ')));
if(errors.length)throw Error(errors.join('\n'));console.log('PASS: authentication, diagnostic state, chat, HTML escaping, mobile overflow, no JS errors');await browser.close();server.close();
})().catch(e=>{console.error(e);process.exit(1)});
